sys:
  web:
    user:
      token-secret-key: "r7X9cLp5Z2v8KbJ3n6F7d4H1m9s0Q8w"



---
spring:
  config:
    activate:
      on-profile: "suyh"

sys:
  web:
    user:
      captcha:
        two-factor-auth-enabled: false


